Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,7 +23,10 @@ jobs:
       run: mvn clean package install
 
     - name: Login to Docker Hub
-      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.SECRET_USERNAME }} --password-stdin || echo "Docker Login Failed"
+      run: |
+        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin || echo "Docker Login Failed"
+
+      # run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.SECRET_USERNAME }} --password-stdin || echo "Docker Login Failed"
       # run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
       # uses: docker/login-action@v1
       # with:
