Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,7 +29,11 @@ jobs:
         run: mvn clean install
 
       - name: Login to Docker Hub
-        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.SECRET_USERNAME }} --password-stdin
+        run: |
+         echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.SECRET_USERNAME }}" --password-stdin || echo "Docker Login Failed"
+
+      # - name: Login to Docker Hub
+      #   run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.SECRET_USERNAME }} --password-stdin
 
       - name: Build Docker Image and Push
         run: |
