Update main.yml
token added now

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,11 +23,12 @@ jobs:
       run: mvn clean package install
 
     - name: Login to Docker Hub
+      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.SECRET_USERNAME }} --password-stdin || echo "Docker Login Failed"
       # run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
-      uses: docker/login-action@v1
-      with:
-         username: ${{secrets.SECRET_USERNAME}}
-         password: ${{secrets.SECRET_PASSWORD}}
+      # uses: docker/login-action@v1
+      # with:
+      #    username: ${{secrets.SECRET_USERNAME}}
+      #    password: ${{secrets.SECRET_PASSWORD}}
 
     - name: Build Docker image
       run: docker build -t jagadeeshb1585/jagadeeshb1585/githubactions:latest .
